### PR TITLE
Reserved underscores

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@hjmjohnson @afni-rickr care to review?

BTW, is there an upstream for znzlib?

**Review by hjmjohnson — APPROVED** [review]
@seanm @afni-rickr 

I agree with all these changes.

**Comment by afni-rickr** [comment]
This looks good, @seanm.  No, znzlib comes with niftilib.  Thanks!

**Comment by seanm** [comment]
Thanks!  I have another patch coming up...

**Pull request merged**
