### PR TITLE
Use ints for base version macros.  Add formatting.

### PR DESCRIPTION
**Pull request by afni-rickr**
@leej3 @hjmjohnson I believe this is what we wanted for the base macros, as ints (with added formatting).

### CODE REVIEW

**Comment by leej3** [comment]
Sure. I can tweak the cmake build for that. Is this change to enforce  version numbers to integers rather than arbitrary strings?

**Comment by afni-rickr** [comment]
Yes, they were were originally given as ints with a later conversion to strings in the TO_STRING macros.  That allows C code to use direct comparisons, if desired.

**Comment by leej3** [comment]
Sounds good. Sorry for missing that detail!

**Comment by afni-rickr** [comment]
Great, thanks!

**Pull request merged**
