### PR TITLE
Fixed some typos / spelling mistakes found with codespell tool

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@afni-rickr @hjmjohnson care to review?

**Comment by seanm** [comment]
@afni-rickr @hjmjohnson friendly ping...

These changes should be very non-controversial.

**Comment by seanm** [comment]
@afni-rickr @hjmjohnson Happy new year!  Friendly ping...

**Comment by seanm** [comment]
@afni-rickr @hjmjohnson so guys, are you just insanely busy?, or is nifti_clib abandonware?, or are my patches unwanted, or of bad quality, or...?  I appreciate that this is open source and no one is obligated to pay any attention to me :), but I and my employer use nifti_clib and just I'd like to understand where it stands... I prefer to upstream my improvements, but I could always switch to using my own fork. Cheers.

**Comment by afni-rickr** [comment]
@seanm.  Insanely busy probably applies, and nifti_clib is not abandonware.  It is difficult to discuss in such a public forum, but the patches have clearly been hit-or-miss for some of us, and much more importantly, they require a lot of time for bickering, which this thread might as well.  The discussions have been very difficult, and with a busy schedule, such time and energy is not well spent.

**Review by hjmjohnson — APPROVED** [review]

**Pull request merged**
